Error CS1061 in Tests
Amended to use the desired syntax in the tests.

Error CS1061 'HistoryList' does not contain a definition for 'Add' and no extension method 'Add' accepting a first argument of type 'HistoryList' could be found (are you missing a using directive or an assembly reference?) EDDiscoveryTests \EDDiscoveryTests\TravelHistoryFilterTests.cs 56 Active
Repeated 5 times